version: '3'
services:
  homeassistant:
    container_name: homeassistant
    image: "ghcr.io/home-assistant/home-assistant:stable"
    env_file:
      - ".env"
    volumes:
      - /home/pi/homeassistant/config:/config
      - /etc/localtime:/etc/localtime:ro
    restart: always
    ports:
      - 8123:8123
    networks:
      - ha_network
    depends_on:
      - zigbee2mqtt

  mosquitto:
    image: eclipse-mosquitto
    container_name: mosquitto
    volumes:
      - /home/pi/homeassistant/mosquitto/config:/mosquitto/config
      - /home/pi/homeassistant/mosquitto/data:/mosquitto/data
      - /home/pi/homeassistant/mosquitto/log:/mosquitto/log
    restart: always
    networks:
      - ha_network

  zigbee2mqtt:
    container_name: zigbee2mqtt
    image: koenkk/zigbee2mqtt:1.34.0
    restart: always
    volumes:
      - /home/pi/homeassistant/zigbee2mqtt:/app/data
      - /run/udev:/run/udev:ro
    ports:
      - 8080:8080
    devices:
      - /dev/ttyUSB0:/dev/ttyACM0
    networks:
      - ha_network
    depends_on:
      - mosquitto

  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: cloudflared
    restart: always
    command: tunnel run
    env_file:
      - ./.env
    networks:
      - ha_network

networks:
  ha_network: